# save as configs/rec/rec_r34_vd_sar.yml
Global:
  use_gpu: true
  epoch_num: 200
  log_smooth_window: 20
  pretrained_model: ./pretrain_models/en_server_resnet34_sar
  checkpoints:
  save_model_dir: ./output/rec_r34_sar
  save_epoch_step: 5
  print_batch_step: 10
  eval_batch_step: [0, 200]
  cal_metric_during_train: True

Architecture:
  model_type: rec
  algorithm: SAR
  Backbone:
    name: ResNet
    layers: 34
  Head:
    name: SARHead
    enc_dim: 512
    max_text_length: 80

Loss:
  name: SARLoss

Optimizer:
  name: Adam
  lr:
    learning_rate: 0.0001

PostProcess:
  name: SARLabelDecode
  max_text_length: 80

Metric:
  name: RecMetric
  main_indicator: acc

Train:
  dataset:
    name: SimpleDataSet
    data_dir: /kaggle/working/output_checks6/rec/train
    label_file_list: ["/kaggle/working/output_checks6/rec/train_list.txt"]
  loader:
    batch_size_per_card: 32
    shuffle: True
    drop_last: True
    num_workers: 4

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: /kaggle/working/output_checks6/rec/val
    label_file_list: ["/kaggle/working/output_checks6/rec/val_list.txt"]
  loader:
    batch_size_per_card: 32
    shuffle: False
    drop_last: False
    num_workers: 4
